version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    networks:
      - gettrip-backend

  backend:
    build: .  #TODO: TBD after github actions task
    env_file:
      - .env
    ports:
      - 8080:5000
    networks:
      - gettrip-backend
      - gettrip-frontend

  frontend:
    build: .  #TODO: TBD after github actions task
    env_file:
      - .env
    ports:
      - 80:5000
    networks:
      - gettrip-frontend

networks:
  gettrip-backend:
  gettrip-frontend:
