version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    networks:
      - gettrip-backend

  backend:
    image: ghcr.io/gettrip/backend:v0.1.1
    env_file:
      - .env
    ports:
      - 8080:5000
    networks:
      - gettrip-backend
      - gettrip-frontend
    volumes:
      - ./config:/webapp/config:ro


  frontend:
    image: ghcr.io/gettrip/frontend:v0.1.0
    env_file:
      - .env
    ports:
      - 80:5000
    networks:
      - gettrip-frontend

networks:
  gettrip-backend:
  gettrip-frontend:
